# General settings
experiment_name: "my_experiment"   # 실험 이름
device: 0   # GPU id (CUDA 사용), CPU 사용하려면 -1
seed: 42  # 랜덤 시드 설정
data_base_path: "E:/ARNIQA/ARNIQA/dataset"  # 데이터셋 경로

# Checkpoint settings
checkpoint_base_path: "E:/ARNIQA/ARNIQA/checkpoints"  # 체크포인트 저장 경로
checkpoint_frequency: 1  # 에폭마다 체크포인트 저장

# Training
training:
  epochs: 10    # 학습할 에폭 수 (기존 10 → 20으로 변경, 필요 시 조정)
  learning_rate: !!float 1e-4    # 학습률 (기존 1e-3 → 1e-4로 감소, 안정적 학습을 위해 조정)
  batch_size: 8     # 배치 크기 (기존 16 → 32로 증가, GPU 메모리 확인 필요)
  lr: !!float 1e-4   # 동일한 학습률 사용
  num_workers: 4   # 데이터 로딩 워커 수 (기존 20 → 8로 감소, 과도한 병렬 처리 방지)
  log_images_frequency: 500  # 로그 이미지 빈도 (기존 1000 → 500으로 조정)
  resume_training: false    # 학습 재개 여부
  step_size: 5  # 학습률 감소 주기
  gamma: 0.5  # 학습률 감소 계수 (기존 0.1 → 0.5로 완화)

  lr_scheduler_t0: 10  # CosineAnnealingWarmRestarts에서 사용할 초기 주기
  lr_scheduler: true


  data:
    patch_size: 224   # 이미지 패치 크기
    max_distortions: 4  # 적용할 최대 왜곡 수
    num_levels: 5   # 왜곡 수준 수
    pristine_prob: 0.05   # 왜곡 미적용 확률

  optimizer:
    name: Adam   # 옵티마이저 변경 (기존 SGD → Adam)
    momentum: 0.9   # SGD에서만 사용 (무시 가능)
    weight_decay: !!float 1e-4    # 가중치 감소 계수




  lr_scheduler:
    name: CosineAnnealingWarmRestarts   # 학습률 스케줄러
    T_0: 5    # 주기 길이 (기존 1 → 5로 변경)
    T_mult: 2   # 주기 배수
    eta_min: !!float 1e-6   # 최소 학습률

# Validation
validation:
  frequency: 1  # 검증 빈도 (1 epoch마다 검증 수행)
  num_splits: 5  # 데이터셋 분할 수 (기존 10 → 5로 감소, 검증 속도 향상)
  alpha: 0.1  # 회귀 분석 alpha 값
  visualize: true   # 임베딩 시각화
  visualization:
    tsne:
      n_components: 2   # t-SNE 차원 수 (3 → 2로 단순화)
      perplexity: 30    # t-SNE perplexity 값
      n_iter: 1000    # 반복 횟수
    umap:
      n_components: 2   # UMAP 차원 수 (3 → 2로 단순화)
      n_neighbors: 15   # UMAP 이웃 수 (기존 25 → 15)
      min_dist: 0.1   # 최소 거리 (기존 0.2 → 0.1)
      metric: euclidean   # 거리 메트릭
  datasets:  # 검증 데이터셋
    - spaq


# Test
test:
  batch_size: 8    # 배치 크기 (기존 16 → 32로 증가)
  num_workers: 4   # 데이터 로딩 워커 수
  num_splits: 5   # 데이터셋 분할 수 (기존 10 → 5로 감소)
  grid_search: true   # 그리드 탐색 활성화
  alpha: 0.1  # 회귀 분석 alpha 값
  crop_size: 224  # 이미지 크기
  datasets:  # 테스트 데이터셋
    - spaq

# Model
model:
  temperature: 0.05    # NT-Xent 손실 온도 값
  encoder:    # 인코더 파라미터
    embedding_dim: 128    # 임베딩 차원 수
    pretrained: true    # 사전 학습 가중치
    use_norm: true    # 임베딩 정규화 여부

# Logging
logging:
  use_wandb: false   # wandb 비활성화
